### ISSUE TITLE
Stacking no longer works correctly

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#30]
Testing commit c775055db54106d9c6ec72ccad733c461578e1da on feature/split-draw-map2a branch:
- After stacking, too many paths drawn, possibly including the paths from the previous un-stacked axis, and some paths are missing (bottom axis in stack seems to have paths only going to top-half of unstacked axis);
- When dragging out of a stack, the above extra/missing paths are clearly noticeable;
- Can no longer drag an axis in and out of drop zone in a single motion (shrunk axis does not resize after moving out of drop zone).

**Comment by Don-Isdale** [comment]
That 3rd point (re. single motion) is something I noted previously and reported, tracking that as a separate issue https://github.com/plantinformatics/pretzel/issues/31 - it dates back some weeks, and likely has a different cause to this issue - recalculation of the drop-out distance.   This issue seems to be : needing to update the g.axis y transform (or possibly the axis y scale) when dropping into any drop zone other than the bottom one on the receiving axis / stack.
Another issue, probably separate : when an axis is dropped out, the new paths are calculated as if it is dropped out to the right of the rightmost stack;  probably should recalculate the adjacencies and paths as the dropped-out axis is dragged across past an axis / stack.

**Comment by Don-Isdale** [comment]
Addressed by commit 19b9a38;  early testing looks OK.

**Comment by gabrielkg** [comment]
First two points fixed in commit 19b9a3861d736332f8f83647d066af3fbfa0b25f.
